<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PD" failures="1" tests="6" name="Surefire test" time="33.162" errors="0" timestamp="2024-08-18T19:12:54 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="@BeforeClass setUpClass" time="0.333">
    <failure type="io.cucumber.core.gherkin.FeatureParserException" message="Failed to parse resource at: file:///C:/Users/ppras/git/SeleniumFrameworkDesign/SeleniumFrameworkDesign/src/test/java/cucumber/TryRestAssured.feature
(9:3): expected: #TagLine, #RuleLine, #Comment, #Empty, got &amp;apos;Scenario : Positive Test of Submitting the order&amp;apos;
(12:5): expected: #TagLine, #RuleLine, #Comment, #Empty, got &amp;apos;Given Logged in with username &amp;lt;name&amp;gt; and password &amp;lt;password&amp;gt;&amp;apos;
(13:5): expected: #TagLine, #RuleLine, #Comment, #Empty, got &amp;apos;When I add product &amp;lt;productName&amp;gt; to Cart&amp;apos;
(14:5): expected: #TagLine, #RuleLine, #Comment, #Empty, got &amp;apos;And Checkout &amp;lt;productName&amp;gt; and submit the order&amp;apos;
(15:5): expected: #TagLine, #RuleLine, #Comment, #Empty, got &amp;apos;Then &amp;quot;THANKYOU FOR THE ORDER.&amp;quot; message is displayed on ConfirmationPage&amp;apos;
(21:0): unexpected end of file, expected: #TagLine, #RuleLine, #Comment, #Empty">
      <![CDATA[io.cucumber.core.gherkin.FeatureParserException: Failed to parse resource at: file:///C:/Users/ppras/git/SeleniumFrameworkDesign/SeleniumFrameworkDesign/src/test/java/cucumber/TryRestAssured.feature
(9:3): expected: #TagLine, #RuleLine, #Comment, #Empty, got 'Scenario : Positive Test of Submitting the order'
(12:5): expected: #TagLine, #RuleLine, #Comment, #Empty, got 'Given Logged in with username <name> and password <password>'
(13:5): expected: #TagLine, #RuleLine, #Comment, #Empty, got 'When I add product <productName> to Cart'
(14:5): expected: #TagLine, #RuleLine, #Comment, #Empty, got 'And Checkout <productName> and submit the order'
(15:5): expected: #TagLine, #RuleLine, #Comment, #Empty, got 'Then "THANKYOU FOR THE ORDER." message is displayed on ConfirmationPage'
(21:0): unexpected end of file, expected: #TagLine, #RuleLine, #Comment, #Empty
at io.cucumber.core.gherkin.messages.GherkinMessagesFeatureParser.parse(GherkinMessagesFeatureParser.java:56)
at io.cucumber.core.feature.FeatureParser.parseResource(FeatureParser.java:46)
at java.base/java.util.function.BiFunction.lambda$andThen$0(BiFunction.java:70)
at io.cucumber.core.resource.ResourceScanner.lambda$processResource$1(ResourceScanner.java:79)
at io.cucumber.core.resource.PathScanner$ResourceFileVisitor.visitFile(PathScanner.java:75)
at io.cucumber.core.resource.PathScanner$ResourceFileVisitor.visitFile(PathScanner.java:60)
at java.base/java.nio.file.Files.walkFileTree(Files.java:2725)
at io.cucumber.core.resource.PathScanner.findResourcesForPath(PathScanner.java:53)
at io.cucumber.core.resource.PathScanner.findResourcesForUri(PathScanner.java:31)
at io.cucumber.core.resource.ResourceScanner.findResourcesForUri(ResourceScanner.java:61)
at io.cucumber.core.resource.ResourceScanner.scanForResourcesUri(ResourceScanner.java:134)
at io.cucumber.core.runtime.FeaturePathFeatureSupplier.loadFeatures(FeaturePathFeatureSupplier.java:62)
at io.cucumber.core.runtime.FeaturePathFeatureSupplier.get(FeaturePathFeatureSupplier.java:45)
at io.cucumber.testng.TestNGCucumberRunner.<init>(TestNGCucumberRunner.java:122)
at io.cucumber.testng.AbstractTestNGCucumberTests.setUpClass(AbstractTestNGCucumberTests.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass setUpClass -->
  <testcase classname="rahulshettyacademy.tests.ErrorValidationsTest" name="LoginErrorValidation" time="0.551">
    <skipped/>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="rahulshettyacademy.tests.ErrorValidationsTest" name="LoginErrorValidation" time="1.104">
    <failure type="java.lang.AssertionError" message="expected [Login Successfully] but found [Incorrect email or password.]">
      <![CDATA[java.lang.AssertionError: expected [Login Successfully] but found [Incorrect email or password.]
at rahulshettyacademy.tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="rahulshettyacademy.tests.ErrorValidationsTest" name="ProductErrorValidation" time="1.92"/>
  <testcase classname="rahulshettyacademy.tests.SubmitOrderTest" name="submitOrder" time="7.874"/>
  <testcase classname="rahulshettyacademy.tests.SubmitOrderTest" name="submitOrder" time="7.28"/>
  <testcase classname="rahulshettyacademy.tests.SubmitOrderTest" name="OrderHistoryTest" time="0.674"/>
</testsuite> <!-- Surefire test -->
